name: Build assets

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build JavaScript assets
    steps:
      - uses: actions/checkout@v2
      - uses: flarum/action-build@master
        with:
          package_manager: yarn
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
